server:
  port: 8761

spring:
  application:
    name: discoveryservice
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: ecommerce

eureka:
  client:
    register-with-eureka: false # 자신의 정보 유레카에 등록하지 않음
    fetch-registry: false # 자신의 정보 유레카에 등록하지 않음
